export default {
  plugins: {
    'postcss-pxtorem': {
      rootValue: 37.5, // 设计稿宽度 375 / 10
      unitPrecision: 5,
      propList: ['*'],
      selectorBlackList: [
        // PC 端样式全部排除
        '.pc-only',
        '.no-rem',
        // Element Plus 组件不转换
        '.el-',
        // 现有组件类名（保持 PC 端现状）- 使用前缀匹配
        '.app-',
        '.filter-',
        '.wallpaper-',
        '.hero-',
        '.container',
        '.header-',
        '.brand-',
        '.view-mode-',
        '.action-',
        '.theme-',
        '.fullscreen-',
        '.github-',
        '.search-',
        '.today-',
        '.main-content',
        '.error-state',
        '.back-to-top',
        '.loading-',
        '.skeleton-',
        '.modal-',
        '.info-',
        '.detail-',
        '.download-',
        '.tag',
        '.btn',
        '.card',
        '.result-',
        '.reset-',
        '.popup-',
        '.option-',
        '.confirm-',
        '.group-',
        '.drawer-',
        '.nav-',
        '.section-',
        '.external-',
        '.about-',
        '.tech-',
        '.contact-',
        '.feature-',
        // 根元素
        'html',
        'body',
      ],
      replace: true,
      mediaQuery: false,
      minPixelValue: 2,
      exclude: /node_modules/i,
    },
  },
}
